spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eyeglasses_store_dev?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  devtools:
    restart:
      enabled: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    com.eyeglasses.eyeglasses_store: DEBUG
    org.springframework.security: DEBUG
